### ISSUE TITLE
wtf is this

### ISSUE THREAD

**Issue by RoseGoldlsntGay** [4wl/ShadyAddons#2]
title

**Comment by 4wl** [comment]
literally

**Comment by rtx3090-ti** [comment]
bruh it’s messed up shady with the hydrogen build files?? too lazy to check for rat

**Comment by 4wl** [comment]
https://cheatersgetbanned.me/ this is original

**Comment by 4wl** [comment]
and its no rat

**Comment by rtx3090-ti** [comment]
is this just a compilable version but with extra jokes?

**Comment by 4wl** [comment]
i dont know
